apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqrbot
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sqrbot
  template:
    metadata:
      labels:
        name: sqrbot
    spec:
      containers:
        - name: sqrbot
          imagePullPolicy: "Always"
          image: "lsstsqre/sqrbot:latest"
          env:
            - name: HUBOT_NAME
              value: "sqrbot"
            - name: HUBOT_SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sqrbot
                  key: slack-token
            - name: HUBOT_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sqrbot
                  key: github-token
            - name: HUBOT_GITHUB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqrbot
                  key: github-password
            - name: HUBOT_GITHUB_USER
              valueFrom:
                secretKeyRef:
                  name: sqrbot
                  key: github-user
            # If you specify these everything gets screwed up
            #  if the username/password are incorrect.
            - name: LSST_JIRA_USER
              valueFrom:
                secretKeyRef:
                  name: sqrbot
                  key: jira-user
            - name: LSST_JIRA_PWD
              valueFrom:
                secretKeyRef:
                  name: sqrbot
                  key: jira-password
            - name: HUBOT_LOG_LEVEL
              value: info
