apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/keeper-sealedsecret.yaml
- resources/cloudsql-sealedsecret.yaml
- github.com/lsst-sqre/ltd-keeper.git//manifests?ref=tickets/DM-27608-3
- resources/keeper-ingress.yaml
- github.com/lsst-sqre/ltd-dasher.git//manifests?ref=0.1.7

patches:
  - patches/keeper-cm.yaml
  - patches/keeper-deployment.yaml

namespace: lsst-the-docs

images:
  - name: lsstsqre/ltd-keeper
    newTag: tickets-DM-27608-3
