apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/keeper-sealedsecret.yaml
- resources/cloudsql-sealedsecret.yaml
- github.com/lsst-sqre/ltd-keeper.git//manifests?ref=1.20.1
- resources/keeper-ingress.yaml
- github.com/lsst-sqre/ltd-dasher.git//manifests?ref=0.1.7

patches:
  - patches/keeper-cm.yaml
  - patches/keeper-deployment.yaml

namespace: lsst-the-docs
