apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/keeper-vaultsecret.yaml
- resources/cloudsql-vaultsecret.yaml
- github.com/lsst-sqre/ltd-keeper.git//manifests?ref=1.22.0
- resources/keeper-ingress.yaml
- github.com/lsst-sqre/ltd-dasher.git//manifests?ref=0.1.10

patches:
  - patches/keeper-cm.yaml
  - patches/keeper-deployment.yaml
  - patches/dasher-deployment.yaml

namespace: lsst-the-docs
