apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/keeper-sealedsecret.yaml
- resources/cloudsql-sealedsecret.yaml
- github.com/lsst-sqre/ltd-keeper.git//manifests?ref=1.21.0
- resources/keeper-ingress.yaml
- github.com/lsst-sqre/ltd-dasher.git//manifests?ref=tickets/DM-27805

patches:
  - patches/keeper-cm.yaml
  - patches/keeper-deployment.yaml
  - patches/dasher-deployment.yaml

namespace: lsst-the-docs

images:
  - name: lsstsqre/ltd-dasher
    newTag: tickets-DM-27805
