apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
spec:
  tls:
    - hosts:
      - monitoring.lsst.codes
      secretName: monitoring-tls
  rules:
    - host: monitoring.lsst.codes
      http:
        paths:
          - path: /chronograf
            pathType: Prefix
            backend:
              serviceName: monitoring-chronograf
              servicePort: 80
          - path: /
            pathType: Prefix
            backend:
              serviceName: monitoring-influxdb2
              servicePort: http
