apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: monitoring
  namespace: monitoring
spec:
  path: {{ .Values.vaultSecretsPath }}/monitoring
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: pull-secret
spec:
  path: {{ .Values.vaultSecretsPath }}/pull-secret
  type: kubernetes.io/dockerconfigjson
