apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: monitoring
  namespace: monitoring
spec:
  path: secret/k8s_operator/roundtable/monitoring
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: pull-secret
spec:
  path: secret/k8s_operator/roundtable/pull-secret
  type: kubernetes.io/dockerconfigjson
