vault:
  global:
    tlsDisable: true

  injector:
    enabled: false

  server:
    image:
      tag: "1.6.0"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-issuer"
      tls:
        - secretName: vault-ingress-tls
          hosts:
            - vault.lsst.codes
            - vault-1.lsst.codes
            - vault-2.lsst.codes
      hosts:
        - host: vault.lsst.codes
          paths:
            - "/"
        - host: vault-1.lsst.codes
          paths:
            - "/"
        - host: vault-2.lsst.codes
          paths:
            - "/"

    # Used by the GCS storage backend.
    extraEnvironmentVars:
      GOOGLE_APPLICATION_CREDENTIALS: "/vault/userconfig/vault-kms-creds/credentials.json"

    extraVolumes:
      - type: "secret"
        name: "vault-kms-creds"

    dataStorage:
      enabled: false

    standalone:
      enabled: false

    ha:
      enabled: true
      replicas: 3

      config: |
        ui = true

        listener "tcp" {
          tls_disable     = 1
          address         = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        seal "gcpckms" {
          credentials = "/vault/userconfig/vault-kms-creds/credentials.json"
          project     = "plasma-geode-127520"
          region      = "global"
          key_ring    = "vault"
          crypto_key  = "vault-seal"
        }

        storage "gcs" {
          bucket     = "storage.vault.lsst.codes"
          ha_enabled = "true"
        }

        service_registration "kubernetes" {}
