apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sqre-admin@lists.lsst.org
    privateKeySecretRef:
      name: vault-letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
