apiVersion: v1
kind: Secret
metadata:
  name: logging-security-config
type: Opaque
stringData:
  config.yml: |-
    _meta:
      type: "config"
      config_version: 2

    config:
      dynamic:
        authc:
          basic_internal_auth_domain:
            http_enabled: true
            transport_enabled: true
            order: 0
            http_authenticator:
              type: basic
              challenge: false
            authentication_backend:
              type: internal
          openid_auth_domain:
            http_enabled: true
            transport_enabled: true
            order: 1
            http_authenticator:
              type: openid
              challenge: false
              config:
                enable_ssl: true
                subject_key: sub
                openid_connect_url: https://roundtable.lsst.codes/.well-known/openid-configuration
            authentication_backend:
              type: noop
