apiVersion: v1
kind: Secret
metadata:
  name: logging-security-config
type: Opaque
stringData:
  config.yml: |-
    _meta:
      type: "config"
      config_version: 2

    config:
      dynamic:
        http:
          xff:
            enabled: true
            internalProxies: "10\\..*"
        authc:
          basic_internal_auth_domain:
            http_enabled: true
            transport_enabled: true
            order: 0
            http_authenticator:
              type: basic
              challenge: false
            authentication_backend:
              type: internal
          proxy_auth_domain:
            http_enabled: true
            transport_enabled: true
            order: 1
            http_authenticator:
              type: proxy
              challenge: false
              config:
                user_header: "X-Auth-Request-User"
                roles_header: "X-Proxy-Roles"
            authentication_backend:
              type: noop
