apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: logging-networkpolicy
spec:
  podSelector:
    matchLabels:
      app: logging-opendistro-es
      role: kibana
    policyTypes:
      - Ingress
    ingress:
      - from:
          - podSelector:
              matchLabels:
                app: nginx-ingress
                component: controller
        ports:
          - protocol: TCP
            port: 5601
