apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: events

nameSuffix: "-jsick"

resources:
  - resources/templatebot-sealedsecret.yaml
  - resources/templatebot-aide-sealedsecret.yaml
  - github.com/lsst-sqre/templatebot.git//manifests/base?ref=0.1.2
  - github.com/lsst-sqre/lsst-templatebot-aide.git//manifests/base?ref=0.3.3

patches:
  - patches/templatebot-configmap.yaml
  - patches/templatebot-deployment.yaml
  - patches/templatebot-aide-configmap.yaml
  - patches/templatebot-aide-deployment.yaml
