apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rubintv-dev

images:
  - name: lsstsqre/rubintv
    newTag: develop

resources:
  - github.com/lsst-sqre/rubin-tv.git//manifests/base?ref=develop
  - resources/secret.yaml
  - resources/ingress.yaml

patches:
  - patches/deployment.yaml
