influxdb2:
  # -- InfluxDB2 admin user; uses admin-password/admin-token keys from
  # secret.
  adminUser:
    organization: "square"
    bucket: "monitoring"
    retention_policy: "30d"
    existingSecret: monitoring
  # -- InfluxDB2 ingress configuration.
  ingress:
    # @default -- False
    enabled: true
    hostname: monitoring.lsst.codes
    tls: true
    secretName: monitoring-tls
    # InfluxDB2 can't run behind a routed path--it must be on the root.
    # Note that this requires a CNAME
    # from: _acme-challenge.<hostname>.<domain>
    # to: _acme-challenge.tls.<domain>
    # cf https://phalanx.lsst.io/ops/cert-issuer/bootstrapping.html
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /
      cert-manager.io/cluster-issuer: cert-issuer-letsencrypt-dns
    path: /
    pathType: Prefix

# -- Path to the Vault secrets (`secret/k8s_operator/<hostname>`)
vaultSecretsPath: "secret/k8s_operator/roundtable"
