apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: events

images:
  - name: lsstsqre/safirdemo
    newTag: 0.1.1

resources:
  - github.com/lsst-sqre/safirdemo.git//manifests/base?ref=0.1.1
