apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: events

images:
  - name: "lsstsqre/ltdevents"
    newTag: "0.1.0"

resources:
  - github.com/lsst-sqre/ltd-events.git//manifests/base?ref=0.1.0

patches:
  - patches/configmap.yaml
  - patches/deployment.yaml
