apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: events

nameSuffix: "-jr"

commonLabels:
  app: sqrbot-jr

resources:
  - resources/vaultsecret.yaml
  - github.com/lsst-sqre/sqrbot-jr.git//manifests/base?ref=0.6.0

patches:
  - patches/configmap.yaml
  - patches/deployment.yaml
