apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: events

images:
  - name: lsstsqre/rubintv
    newTag: 0.1.15

resources:
  - github.com/lsst-sqre/rubin-tv.git//manifests/base?ref=0.1.16
  - resources/secret.yaml
