apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: events

images:
  - name: lsstsqre/rubintv
    newTag: tickets-DM-35341

resources:
  - github.com/lsst-sqre/rubin-tv.git//manifests/base?ref=0.1.4
  - resources/secret.yaml
