apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: events

images:
  - name: lsstsqre/rubintv
    newTag: 1.1.0

resources:
  - github.com/lsst-sqre/rubin-tv.git//manifests/base?ref=1.1.0
  - resources/secret.yaml

patches:
  - patches/deployment.yaml
