apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: events

images:
  - name: lsstsqre/rubintv
    newTag: tickets-DM-31998

resources:
  - github.com/lsst-sqre/rubin-tv.git//manifests/base?ref=tickets/DM-31998
  - resources/secret.yaml
