apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: lsstsqre/strimzi-registry-operator
    newTag: tickets-DM-33317

resources:
  - resources/kafka.yaml
  # Schema Registry
  - resources/schemaregistry-user.yaml
  - github.com/lsst-sqre/strimzi-registry-operator.git//manifests?ref=tickets/DM-33317
  - resources/schemaregistry.yaml
  - resources/schemas-topic.yaml
  # Kafka topics
  - resources/sqrbot-jr-topics.yaml
  - resources/templatebot-topics.yaml
  - resources/sqrbot-jsick-topics.yaml
  - resources/templatebot-jsick-topics.yaml
  - resources/ltdevents-topics.yaml
  - resources/ook-topics.yaml
  # Kafka users
  - resources/demo-user.yaml
  - resources/sqrbot-jr-user.yaml
  - resources/templatebot-user.yaml
  - resources/sqrbot-jsick-user.yaml
  - resources/templatebot-jsick-user.yaml
  - resources/ltdevents-user.yaml
  - resources/ook-user.yaml

namespace: events
