apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: events

resources:
  - resources/templatebot-vaultsecret.yaml
  - resources/templatebot-aide-vaultsecret.yaml
  - github.com/lsst-sqre/templatebot.git//manifests/base?ref=0.2.0
  - github.com/lsst-sqre/lsst-templatebot-aide.git//manifests/base?ref=0.6.0

patchesStrategicMerge:
  - patches/templatebot-configmap.yaml
  - patches/templatebot-deployment.yaml
  - patches/templatebot-aide-configmap.yaml
  - patches/templatebot-aide-deployment.yaml

images:
  - name: lsstsqre/templatebot-aide
    # newTag: 0.6.0
    newTag: tickets-DM-41781
    newName: ghcr.io/lsst-sqre/templatebot-aide
#   - name: lsstsqre/templatebot
#     newTag: tickets-DM-32710
