apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: chronograf
  namespace: chronograf
spec:
  path: secret/k8s-operator/roundtable/chronograf
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: chronograf-oauth
  namespace: chronograf
spec:
  path: secret/k8s-operator/roundtable/chronograf-oauth
  type: Opaque
