---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: events
spec:
  kafka:
    version: 3.2.0
    replicas: 3
    listeners:
    - name: tls
      port: 9093
      type: internal
      tls: true
      authentication:
        type: tls
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: 2.3
    storage:
      type: persistent-claim
      size: 100Gi
      class: faster
    authorization:
      type: simple
    jvmOptions:
      "-Xmx": 512M
      "-Xms": 512M
    resources:
      limits:
        memory: 4Gi
        cpu: 1
      requests:
        memory: 2Gi
        cpu: 500m
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: events-kafka-jmx-exporter-configuration.yaml
          name: events-kafka-jmx-exporter-configuration
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: dedicated
                  operator: In
                  values:
                  - events
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: strimzi.io/name
                  operator: In
                  values:
                  - events-kafka
              topologyKey: kubernetes.io/hostname
        tolerations:
        - effect: NoExecute
          key: dedicated
          operator: Equal
          value: events
      persistentVolumeClaim:
        metadata:
          annotations:
            argocd.argoproj.io/compare-options: IgnoreExtraneous
            argocd.argoproj.io/sync-options: Prune=false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 50Gi
      class: faster
    jvmOptions:
      "-Xmx": 512M
      "-Xms": 512M
    resources:
      limits:
        memory: 3Gi
        cpu: 1
      requests:
        memory: 2Gi
        cpu: 500m
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: dedicated
                  operator: In
                  values:
                  - events
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: strimzi.io/name
                  operator: In
                  values:
                  - events-zookeeper
              topologyKey: kubernetes.io/hostname
        tolerations:
        - effect: NoExecute
          key: dedicated
          operator: Equal
          value: events
      persistentVolumeClaim:
        metadata:
          annotations:
            argocd.argoproj.io/compare-options: IgnoreExtraneous
            argocd.argoproj.io/sync-options: Prune=false
  entityOperator:
    topicOperator:
      watchedNamespace: events
    userOperator:
      watchedNamespace: events
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: events-kafka-jmx-exporter-configuration
data:
  events-kafka-jmx-exporter-configuration.yaml: |
    lowercaseOutputName: true
