---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ltd.events
  labels:
    strimzi.io/cluster: events
spec:
  partitions: 8
  replicas: 3
  config:
    retention.ms: 2592000000
