---
# For the ook-queue consumer group
# This user reads ltd.events and writes to ook.queue
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: kafkauser-ook-queue
  labels:
    strimzi.io/cluster: events
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Produce ook.ingest
      - resource:
          type: topic
          name: "ook.ingest"
          patternType: literal
        operation: "Write"
        type: "allow"
      - resource:
          type: topic
          name: "ook.ingest"
          patternType: literal
        operation: "Describe"
        type: "allow"
      # Access ook-queue consumer group
      - resource:
          type: "group"
          name: "ook-queue"
          patternType: "literal"
        operation: "Describe"
        type: "allow"
      - resource:
          type: "group"
          name: "ook-queue"
          patternType: "literal"
        operation: "Read"
        type: "allow"
      # Consume the ltd.events topic
      - resource:
          type: "topic"
          name: "ltd.events"
          patternType: "literal"
        operation: "Read"
        type: "allow"
      - resource:
          type: "topic"
          name: "ltd.events"
          patternType: "literal"
        operation: "Describe"
        type: "allow"
---
# For the ook-ingest consumer group
# This user reads ook.queue
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: kafkauser-ook-ingest
  labels:
    strimzi.io/cluster: events
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Access ook-ingest consumer group
      - resource:
          type: "group"
          name: "ook-ingest"
          patternType: "literal"
        operation: "Describe"
        type: "allow"
      - resource:
          type: "group"
          name: "ook-ingest"
          patternType: "literal"
        operation: "Read"
        type: "allow"
      # Consume the ook.ingest topic
      - resource:
          type: "topic"
          name: "ook.ingest"
          patternType: "literal"
        operation: "Read"
        type: "allow"
      - resource:
          type: "topic"
          name: "ook.ingest"
          patternType: "literal"
        operation: "Describe"
        type: "allow"
