---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafkauser-ook-queue
  labels:
    strimzi.io/cluster: events
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: ook.ingest
        patternType: literal
      operation: Write
      type: allow
    - resource:
        type: topic
        name: ook.ingest
        patternType: literal
      operation: Describe
      type: allow
    - resource:
        type: group
        name: ook-queue
        patternType: literal
      operation: Describe
      type: allow
    - resource:
        type: group
        name: ook-queue
        patternType: literal
      operation: Read
      type: allow
    - resource:
        type: topic
        name: ltd.events
        patternType: literal
      operation: Read
      type: allow
    - resource:
        type: topic
        name: ltd.events
        patternType: literal
      operation: Describe
      type: allow
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafkauser-ook-ingest
  labels:
    strimzi.io/cluster: events
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    - resource:
        type: group
        name: ook-ingest
        patternType: literal
      operation: Describe
      type: allow
    - resource:
        type: group
        name: ook-ingest
        patternType: literal
      operation: Read
      type: allow
    - resource:
        type: topic
        name: ook.ingest
        patternType: literal
      operation: Read
      type: allow
    - resource:
        type: topic
        name: ook.ingest
        patternType: literal
      operation: Describe
      type: allow
