---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: "ook.ingest"
  labels:
    strimzi.io/cluster: events
spec:
  partitions: 16
  replicas: 3
  config:
    # http://kafka.apache.org/documentation/#topicconfigs
    retention.ms: 604800000 # 7 days
