---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ook.ingest
  labels:
    strimzi.io/cluster: events
spec:
  partitions: 16
  replicas: 3
  config:
    retention.ms: 604800000
