---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: schemaregistry
  labels:
    strimzi.io/cluster: events
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: registry-schemas
        patternType: literal
      operation: All
      type: allow
    - resource:
        type: group
        name: schema-registry
        patternType: prefix
      operation: All
      type: allow
    - resource:
        type: topic
        name: __consumer_offsets
        patternType: literal
      operation: Describe
      type: allow
    - resource:
        type: topic
        name: __consumer_offsets
        patternType: literal
      operation: DescribeConfigs
      type: allow
