---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafkauser-sqrbot-jr
  labels:
    strimzi.io/cluster: events
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: sqrbot.interaction
        patternType: literal
      operation: Write
      type: allow
    - resource:
        type: topic
        name: sqrbot.interaction
        patternType: literal
      operation: Describe
      type: allow
    - resource:
        type: topic
        name: sqrbot.app.mention
        patternType: literal
      operation: Write
      type: allow
    - resource:
        type: topic
        name: sqrbot.app.mention
        patternType: literal
      operation: Describe
      type: allow
    - resource:
        type: topic
        name: sqrbot.message.channels
        patternType: literal
      operation: Write
      type: allow
    - resource:
        type: topic
        name: sqrbot.message.channels
        patternType: literal
      operation: Describe
      type: allow
    - resource:
        type: topic
        name: sqrbot.message.groups
        patternType: literal
      operation: Write
      type: allow
    - resource:
        type: topic
        name: sqrbot.message.groups
        patternType: literal
      operation: Describe
      type: allow
    - resource:
        type: topic
        name: sqrbot.message.mpim
        patternType: literal
      operation: Write
      type: allow
    - resource:
        type: topic
        name: sqrbot.message.mpim
        patternType: literal
      operation: Describe
      type: allow
    - resource:
        type: topic
        name: sqrbot.message.im
        patternType: literal
      operation: Write
      type: allow
    - resource:
        type: topic
        name: sqrbot.message.im
        patternType: literal
      operation: Describe
      type: allow
