---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sqrbot.jsick.interaction
  labels:
    strimzi.io/cluster: events
spec:
  partitions: 4
  replicas: 3
  config:
    retention.ms: 1800000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sqrbot.jsick.app.mention
  labels:
    strimzi.io/cluster: events
spec:
  partitions: 4
  replicas: 3
  config:
    retention.ms: 1800000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sqrbot.jsick.message.channels
  labels:
    strimzi.io/cluster: events
spec:
  partitions: 4
  replicas: 3
  config:
    retention.ms: 1800000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sqrbot.jsick.message.groups
  labels:
    strimzi.io/cluster: events
spec:
  partitions: 4
  replicas: 3
  config:
    retention.ms: 1800000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sqrbot.jsick.message.im
  labels:
    strimzi.io/cluster: events
spec:
  partitions: 4
  replicas: 3
  config:
    retention.ms: 1800000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sqrbot.jsick.message.mpim
  labels:
    strimzi.io/cluster: events
spec:
  partitions: 4
  replicas: 3
  config:
    retention.ms: 1800000
