---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafkauser-sqrbot-jsick
  labels:
    strimzi.io/cluster: events
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: sqrbot.jsick
        patternType: prefix
      operation: Write
      type: allow
    - resource:
        type: topic
        name: sqrbot.jsick
        patternType: prefix
      operation: Describe
      type: allow
