apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.8.7
- resources/argocd-ui-ingress.yaml
- resources/argocd-grpc-ingress.yaml
- resources/argocd-metrics.yaml
- resources/argocd-server-metrics.yaml
- resources/argocd-repo-server-metrics.yaml
- resources/argocd-grafana-dashboard-cm.yaml

patchesStrategicMerge:
- patches/argocd-cm.yaml
- patches/argocd-rbac-cm.yaml
- patches/argocd-server-service.yaml
- patches/argocd-server-deployment.yaml

# Adds the argocd namespace to all resources, which is required anyhow.
namespace: argocd
