nginx-ingress:
  controller:
    config:
      compute-full-forwarded-for: "true"
      use-forwarded-headers: "true"
    metrics:
      enabled: true
    publishService:
      enabled: true
    service:
      externalTrafficPolicy: Local
