apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |
    [global_tags]
      cluster = "roundtable"
    [agent]
      hostname = "$HOSTNAME"
      omit_hostname = true
      interval = "300s"
      flush_interval = "300s"
      logfile = ""
      collection_jitter = "30s"
      metric_batch_size = 10000
      metric_buffer_limit = 100000

    [[processors.enum]]
      [[processors.enum.mapping]]
        dest = "status_code"
        field = "status"
        [processors.enum.mapping.value_mappings]
          healthy = 1
          problem = 2
          critical = 3

    [[inputs.internal]]
      collect_memstats = false

    [[inputs.prometheus]]
      metric_version = 2
      name_override = "prometheus_influxdb2"
      urls = [
        "https://monitoring.lsst.codes/metrics"
      ]
      [inputs.prometheus.tags]
        prometheus_app = "influxdb2"

    [[outputs.influxdb_v2]]
      bucket = "roundtable_prometheus_"
      organization = "square"
      token = "$INFLUX_TOKEN"
      urls = [
        "https://monitoring.lsst.codes"
      ]
      [outputs.influxdb_v2.tagpass]
        prometheus_app = [
          "influxdb2"
        ]
