apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: telegraf
  namespace: telegraf
spec:
  path: secret/k8s_operator/roundtable/telegraf
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: pull-secret
spec:
  path: secret/k8s_operator/roundtable/pull-secret
  type: kubernetes.io/dockerconfigjson
