neophile:
  vaultSecretsPath: "secret/k8s_operator/roundtable/neophile"
  config:
    githubEmail: "24442459+sqrbot@users.noreply.github.com"
    githubUser: "sqrbot"
    repositories:
      - owner: "lsst-sqre"
        repo: "cachemachine"
      - owner: "lsst-sqre"
        repo: "checkerboard"
      - owner: "lsst-sqre"
        repo: "crawlspace"
      - owner: "lsst-sqre"
        repo: "datalinker"
      - owner: "lsst-sqre"
        repo: "documenteer"
      - owner: "lsst-sqre"
        repo: "gafaelfawr"
      - owner: "lsst-sqre"
        repo: "jupyterlab-controller"
      # faust-avro depends on an ancient version of fastavro, which does not
      # have wheels for Python 3.11
      # - owner: "lsst-sqre"
      #   repo: "kafka-aggregator"
      - owner: "lsst-sqre"
        repo: "kafka-connect-manager"
      - owner: "lsst-sqre"
        repo: "lsst-templatebot-aide"
      - owner: "lsst-sqre"
        repo: "ltd-conveyor"
      - owner: "lsst-sqre"
        repo: "mobu"
      - owner: "lsst-sqre"
        repo: "moneypenny"
      - owner: "lsst-sqre"
        repo: "neophile"
      - owner: "lsst-sqre"
        repo: "nublado2"
      # Ignore during active development
      # - owner: "lsst-sqre"
      #   repo: "noteburst"
      - owner: "lsst-sqre"
        repo: "ook"
      - owner: "lsst-sqre"
        repo: "rsp-restspawner"
      - owner: "lsst-sqre"
        repo: "rubin-tv"
      - owner: "lsst-sqre"
        repo: "safir"
      - owner: "lsst-sqre"
        repo: "safirdemo"
      - owner: "lsst-sqre"
        repo: "segwarides"
      - owner: "lsst-sqre"
        repo: "semaphore"
      - owner: "lsst-sqre"
        repo: "sherlock"
      - owner: "lsst-sqre"
        repo: "strimzi-registry-operator"
      # Disabled while Kafka requires Python 3.9
      # - owner: "lsst-sqre"
      #   repo: "templatebot"
      - owner: "lsst-sqre"
        repo: "templatekit"
      # Ignore during active development
      # - owner: "lsst-sqre"
      #   repo: "times-square"
      - owner: "lsst-sqre"
        repo: "vo-cutouts"
