kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-issuer"
      hosts:
        - monitoring.roundtable.lsst.codes
      tls:
        - secretName: grafana-ingress-tls
          hosts:
            - monitoring.roundtable.lsst.codes

    persistence:
      enabled: true
      size: "10Gi"
      storageClassName: "standard"

    sidecar:
      dashboards:
        enabled: true
        label: "grafana_dashboard"
        searchNamespace: "ALL"

    # Secret resource that contains environment variables for e.g.
    # the GitHub auth client secret.
    envFromSecret: "grafana-env"

    grafana.ini:
      server:
        root_url: "https://monitoring.roundtable.lsst.codes"
      auth.github:
        enabled: true
        allow_sign_up: true
        client_id: "73863e794667b769be29"
        scopes: "user:email,read:org"
        auth_url: "https://github.com/login/oauth/authorize"
        token_url: "https://github.com/login/oauth/access_token"
        api_url: "https://api.github.com/user"
        # Comma-delimited list to GitHub teams
        # 3408969: @lsst-sqre/roundtable-ops
        team_ids: "3408969"
        # Space-delimited list of GitHub organization
        allowed_organizations: "lsst-sqre"

  prometheusOperator:
    admissionWebhooks:
      enabled: false

  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          # Request SSD persistent volume for Prometheus data.
          spec:
            storageClassName: "faster"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: "10Gi"
