apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rubintv-dev
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - host: roundtable.lsst.codes
      http:
        paths:
          - path: /rubintv-dev
            backend:
              serviceName: rubintv
              servicePort: 8080
