apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rubintv-dev
spec:
  ingressClassName: "nginx"
  rules:
    - host: roundtable.lsst.codes
      http:
        paths:
          - path: /rubintv-dev
            pathType: Prefix
            backend:
              service:
                name: rubintv
                port:
                  number: 8080
