apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: roundtable-ingress
  namespace: events
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
spec:
  tls:
    - hosts:
      - roundtable.lsst.codes
      secretName: roundtable-ingress-tls
  rules:
    - host: roundtable.lsst.codes
      http:
        paths:
          - path: /checkerboard
            backend:
              serviceName: checkerboard
              servicePort: 8080
          - path: /ltdevents
            backend:
              serviceName: ltdevents
              servicePort: 8080
          - path: /safirdemo
            backend:
              serviceName: safirdemo
              servicePort: 8080
          - path: /sqrbot-jr
            backend:
              serviceName: sqrbot-jr
              servicePort: 8080
          - path: /sqrbot-jsick
            backend:
              serviceName: sqrbot-jsick
              servicePort: 8080
          - path: /segwarides
            backend:
              serviceName: segwarides
              servicePort: 8080
