apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: roundtable-ingress
  namespace: events
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - "roundtable.lsst.codes"
      secretName: "roundtable-ingress-tls"
  rules:
    - host: "roundtable.lsst.codes"
      http:
        paths:
          - path: "/checkerboard"
            pathType: Prefix
            backend:
              service:
                name: "checkerboard"
                port:
                  number: 8080
          - path: "/ltdevents"
            pathType: Prefix
            backend:
              service:
                name: "ltdevents"
                port:
                  number: 8080
          - path: "/sqrbot-jr"
            pathType: Prefix
            backend:
              service:
                name: "sqrbot-jr"
                port:
                  number: 8080
          - path: "/sqrbot-jsick"
            pathType: Prefix
            backend:
              service:
                name: "sqrbot-jsick"
                port:
                  number: 8080
          - path: "/segwarides"
            pathType: Prefix
            backend:
              service:
                name: "segwarides"
                port:
                  number: 8080
