apiVersion: v1
kind: Namespace
metadata:
  name: rubintv-dev
  labels:
    app: rubintv-dev
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rubintv-dev
spec:
  destination:
    namespace: rubintv-dev
    server: https://kubernetes.default.svc
  project: default
  source:
  path: deployments/rubintv-dev
    repoURL: https://github.com/lsst-sqre/roundtable
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
