apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegraf
spec:
  destination:
    namespace: telegraf
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/telegraf
    repoURL: https://github.com/lsst-sqre/roundtable
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
