apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sherlock
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/app-root: "/"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
spec:
  tls:
    - hosts:
      - status.lsst.codes
      secretName: sherlock-ingress-tls
  rules:
    - host: status.lsst.codes
      http:
        paths:
          - path: /
            backend:
              serviceName: sherlock
              servicePort: sherlock-http
