name: CI

on:
  push:
    branches-ignore:
      - "master"

jobs:
  helm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: lint
