---
# Configuration for the ook-queue deployment
apiVersion: v1
kind: ConfigMap
metadata:
  name: ook-queue
data:
  SAFIR_NAME: "ook"
  SAFIR_PROFILE: "production"
  SAFIR_LOGGER: "ook"
  SAFIR_LOG_LEVEL: "INFO"
  SAFIR_KAFKA_PROTOCOL: "SSL"
  SAFIR_KAFKA_BROKER_URL: "events-kafka-bootstrap:9093"
  SAFIR_KAFKA_CLUSTER_CA: "/var/strimzi-broker/ca.crt"
  SAFIR_KAFKA_CLIENT_CA: "/var/strimzi-client/ca.crt"
  SAFIR_KAFKA_CLIENT_CERT: "/var/strimzi-client/user.crt"
  SAFIR_KAFKA_CLIENT_KEY: "/var/strimzi-client/user.key"
  SAFIR_SCHEMA_REGISTRY_URL: "http://schemaregistry:8081"
  SAFIR_SCHEMA_SUFFIX: ""
  SAFIR_SCHEMA_COMPATIBILITY: "FORWARD_TRANSITIVE"
  ENABLE_LTD_EVENTS_KAFKA_TOPIC: "true"
  ENABLE_OOK_INGEST_KAFKA_TOPIC: "false"
  LTD_EVENTS_KAFKA_TOPIC: "ltd.events"
  OOK_GROUP_ID: "ook-queue"
---
# Configuration for the ook-queue deployment
apiVersion: v1
kind: ConfigMap
metadata:
  name: ook-ingest
data:
  SAFIR_NAME: "ook"
  SAFIR_PROFILE: "production"
  SAFIR_LOGGER: "ook"
  SAFIR_LOG_LEVEL: "INFO"
  SAFIR_KAFKA_PROTOCOL: "SSL"
  SAFIR_KAFKA_BROKER_URL: "events-kafka-bootstrap:9093"
  SAFIR_KAFKA_CLUSTER_CA: "/var/strimzi-broker/ca.crt"
  SAFIR_KAFKA_CLIENT_CA: "/var/strimzi-client/ca.crt"
  SAFIR_KAFKA_CLIENT_CERT: "/var/strimzi-client/user.crt"
  SAFIR_KAFKA_CLIENT_KEY: "/var/strimzi-client/user.key"
  SAFIR_SCHEMA_REGISTRY_URL: "http://schemaregistry:8081"
  SAFIR_SCHEMA_SUFFIX: ""
  SAFIR_SCHEMA_COMPATIBILITY: "FORWARD_TRANSITIVE"
  ENABLE_LTD_EVENTS_KAFKA_TOPIC: "false"
  ENABLE_OOK_INGEST_KAFKA_TOPIC: "true"
  OOK_INGEST_KAFKA_TOPIC: "ook.ingest"
  OOK_GROUP_ID: "ook-ingest"
  ALGOLIA_APP_ID: "0OJETYIVL5"
  ALGOLIA_DOCUMENT_INDEX: "document_dev"
