apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-server-metrics
  labels:
    # Match Prometheus's serviceMonitorSelector.matchLabels
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      # Labels for metrics Service
      app.kubernetes.io/name: argocd-server
  endpoints:
  - port: metrics
