apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-grpc
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
      - grpc.cd.roundtable.lsst.codes
      secretName: argocd-grpc-ingress-tls
  rules:
    - host: grpc.cd.roundtable.lsst.codes
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  name: https
